### PR TITLE
Removes use of characters

### PR DESCRIPTION
**Pull request by allenhumphreys**
Addresses #15 

Removes the use of `characters` and the convenience methods that were created to work around the cumbersome API.

### CODE REVIEW

**Comment by gkaimakas** [comment]
Thanks for the PR

**Comment by allenhumphreys** [comment]
No problem, any chance you could do a release with this within the next week?

**Comment by gkaimakas** [comment]
Yes will do it ASAP

**Comment by gkaimakas** [comment]
Version 7.0.2 should be available shortly

**Pull request merged**
